api.port: 80
api.version: "/v1"

db.engine: 'mongo'
db.mongo.host: 'localhost'
db.mongo.port: '27017'
db.mongo.database: 'secret'
db.mongo.username: 'root'
db.mongo.password: 'root'

log.level: "debug"