version: '3'
services:
  secret-server:
    build: .
    ports:
    - '80:80'
    environment:
      SERVER_PORT: 80
      API_VERSION: v1
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: secret
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      LOG_LEVEL: debug

  mongo:
    image: mongo
    ports:
    - '27017:27017'
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    - MONGO_INITDB_DATABASE=secret
