version: '3'
services:
  secret-server:
    build: .
    ports: 
    - '80:80'

  prometheus:
    image: 'prom/prometheus:latest'
    ports:
    - '9090:9090'
    volumes:
    - './prometheus.yml:/etc/prometheus/prometheus.yml'
