version: '3'
services:
  secret-server:
    build: .
    ports: 
    - '80:80'
  
  mongo:
    image: mongo
    ports:
    - '27017:27017'
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    - MONGO_INITDB_DATABASE=secret
